package com.google.android.glass.sample.compass;


import com.google.android.glass.media.Sounds;
import com.google.android.glass.widget.CardBuilder;
import com.google.android.glass.widget.CardScrollAdapter;
import com.google.android.glass.widget.CardScrollView;

import android.app.Activity;
import android.content.Context;
import android.media.AudioManager;
import android.os.Bundle;
import android.view.View;
import android.view.ViewGroup;
import android.widget.AdapterView;

import java.util.ArrayList;

/**
 * An {@link Activity} showing a tuggable "Hello World!" card.
 * <p>
 * The main content view is composed of a one-card {@link CardScrollView} that provides tugging
 * feedback to the user when swipe gestures are detected.
 * If your Glassware intends to intercept swipe gestures, you should set the content view directly
 * and use a {@link com.google.android.glass.touchpad.GestureDetector}.
 * @see <a href="https://developers.google.com/glass/develop/gdk/touch">GDK Developer Guide</a>
 */
public class Hours extends Activity {

    /** {@link CardScrollView} to use as the main content view. */
    private CardScrollView mCardScroller;
    private CardScrollAdapter mAdapter;

    // /** "Hello World!" {@link View} generated by {@link #buildView()}. */
    private View mView;

    @Override
    protected void onCreate(Bundle bundle) {
        super.onCreate(bundle);


        ArrayList<CardBuilder> cards = new ArrayList<CardBuilder>();

        cards.add(0, new CardBuilder(this, CardBuilder.Layout.AUTHOR)
                        .setHeading("Monday")
                        .setText("7:00 AM - 10:00 PM")
        );
        cards.add(1, new CardBuilder(this, CardBuilder.Layout.AUTHOR)
                        .setHeading("Tuesday")
                        .setText("7:00 AM - 10:00 PM")
        );
        cards.add(2, new CardBuilder(this, CardBuilder.Layout.AUTHOR)
                        .setHeading("Wednesday")
                        .setText("7:00 AM - 10:00 PM")
        );
        cards.add(3, new CardBuilder(this, CardBuilder.Layout.AUTHOR)
                        .setHeading("Thursday")
                        .setText("7:00 AM - 10:00 PM")
        );
        cards.add(4, new CardBuilder(this, CardBuilder.Layout.AUTHOR)
                        .setHeading("Friday")
                        .setText("7:00 AM - 10:00 PM")
        );
        cards.add(5, new CardBuilder(this, CardBuilder.Layout.AUTHOR)
                        .setHeading("Saturday")
                        .setText("7:00 AM - 10:00 PM")
        );
        cards.add(6, new CardBuilder(this, CardBuilder.Layout.AUTHOR)
                        .setHeading("Sunday")
                        .setText("7:00 AM - 10:00 PM")
        );

        mAdapter = new CardAdapter( cards );
        mCardScroller = new CardScrollView(this);
        mCardScroller.setAdapter(mAdapter);
        setContentView(mCardScroller);
    }

    @Override
    protected void onResume() {
        super.onResume();
        mCardScroller.activate();
    }

    @Override
    protected void onPause() {
        mCardScroller.deactivate();
        super.onPause();
    }


}
